version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    ports:
      - '3306:3306'

  api:
    build:
      context: .
    depends_on:
      - db
    env_file: .env
    restart: always
    ports:
      - '8080:8080'
