@id={{create.response.body.id}}

# @name getAll
GET {{baseUrl}}/genres

###

# @name create
POST {{baseUrl}}/genres
Content-Type: application/json

{
  "name": "jose-{{$guid}}"
}
###

# @name getOne
GET {{baseUrl}}/genres/{{id}}

###

# @name update
PUT {{baseUrl}}/genres/{{id}}

{
  "name": "potato-{{$guid}}"
}
###

# @name remove
DELETE {{baseUrl}}/genres/{{id}}

###
