@baseUrl=http://localhost:8080/movies
@id={{create.response.body.id}}

# @name getAll
GET {{baseUrl}}

###

# @name create
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "potato-{{$guid}}",
  "synopsis": "A movie about potatoes.",
  "releasedAt": "2023-10-01T00:00:00.000Z",
  "runtimeInMinutes": 120
}
###

# @name getOne
GET {{baseUrl}}/{{id}}

###

# @name update
PUT {{baseUrl}}/{{id}}

{
  "name": "potato-{{$guid}}",
  "synopsis": "Still a movie about potatoes.",
  "releasedAt": "2023-10-01T00:00:00.000Z",
  "runtimeInMinutes": 120,
  "genreId": 1
}
###

# @name remove
DELETE {{baseUrl}}/{{id}}

###
