name: CI Pipeline

on:
  push:
    branches: [ "feature/**", "develop" ]
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "doc"
      - "LICENSE"
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: movies
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: HatsuneMiku3939/direnv-action@v1
        with:
            direnvVersion: 2.32.1
            masks: SECRET1, SECRET2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test